# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='domain',
            field=models.CharField(default='ncaa.org', max_length=500),
        ),
    ]
