# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0002_university_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='kid_enrolled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='miles_ran',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
