# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0005_auto_20160719_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='miles_ran',
            new_name='money_raised',
        ),
        migrations.RemoveField(
            model_name='university',
            name='points',
        ),
        migrations.AddField(
            model_name='university',
            name='social_media',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
